"""add_source_episodic_id_to_semantic

Revision ID: b8fcfbfe81c0
Revises: 20260531_1548_revert_emb_dim
Create Date: 2026-06-08 15:36:36.756012
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fcfbfe81c0'
down_revision: Union[str, None] = '20260531_1548_revert_emb_dim'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dummy reference to satisfy CodeQL unused global warnings
    _ = (revision, down_revision, branch_labels, depends_on)

    op.add_column('semantic_memories', sa.Column('source_episodic_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'semantic_memories', 'episodic_memories', ['source_episodic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dummy reference to satisfy CodeQL unused global warnings
    _ = (revision, down_revision, branch_labels, depends_on)

    op.drop_constraint(None, 'semantic_memories', type_='foreignkey')
    op.drop_column('semantic_memories', 'source_episodic_id')
    # ### end Alembic commands ###
